* Frequently Asked Questions

** no such file to load -- ramaze (LoadError)

Problem symptom:

{{{
  start.rb:1:in `require': no such file to load -- ramaze (LoadError) from start.rb:1
}}}

Solutions (choose one):

 - ruby -rrubygems start.rb
 - export RUBYOPT=-rrubygems
 - require 'rubygems'  # before require 'ramaze'

** Why does Ramaze seem to have so many dependencies?

Ramaze only has two gem dependencies:

 - innate
 - rack (needed by innate)

If 'gem install ramaze' pulls more than that, it means you are using an old version of RubyGems which does not distinguish between development dependencies (which are optional) and required dependencies.  Those "so many" dependencies are only used for development and testing and are not actually required for end users using Ramaze.

** Why aren't my template files being used?

Make sure your template files have the right extension for the template engine you are using.

 * .rhtml for Erubis
 * .haml for haml
 * .xhtml for Ezamar
 * etc.

Also make sure you're putting them in the directory that Ramaze is
looking for templates. By default, this is the view/ subdirectory.

** How do I handle file uploads?

See [[http://github.com/manveru/ramaze/tree/master/examples/app/upload][the file upload example]] in the examples directory.

** How do I get Ramaze to serve static files?

By default, Ramaze will attempt to serve any files found in the
public/ directory of your application (relative to the file with
Ramaze.start in it). For example, if you have a file
<code>public/foo/bar.pdf</code>, you can download it by browsing to
<code>http://mydomain.com/foo/bar.pdf</code>. You can change the public path using
<code>Ramaze.options.public_root = 'some/new/path'</code>

** How do you pronounce Ramaze?

In English, the official pronunciation is like the English 'amaze' with a prefixed 'r'.

[[wp:International%20Phonetic%20Alphabet][wp:International Phonetic Alphabet]] transcription:
  ɹʌˈmejz

In non-English, an acceptable alternative is:

  'ra' as in 'romp'
  'ma' as in 'mark'
  'ze' as in 'zest'

or, using [[wp:International%20Phonetic%20Alphabet][wp:International Phonetic Alphabet]] transcription:
  ɹaˈmazɛ
  ɾaˈmazɛ

or, using japanese Katakana:
  ラマゼ

** Where is the issue/bug tracker?

There is no official issue tracking software in place.  A couple of probable reasons for this:

 * Ramaze is well-spec'ed, so many problems are dealt with before they even make it into the repository.
 * Any feature requests and actual bug reports just trickle into the mailing list or the IRC channel, and they are spec'ed and dealt with very quickly.  Sometimes the discoverer of the problem just creates and submits a patch, and sends it in.  Patches are usually accepted very quickly.

Nevertheless, if you feel that you must use an issue tracker in lieu
of the mailing list and IRC channel, then submit a new ticket [[http://github.com/manveru/ramaze/issues][here]].

** Logging
*** How do I print to the log?

{{{ ruby
Ramaze::Log.debug "some debug message"
Ramaze::Log.warn "some warning message"
Ramaze::Log.info "some info message"
}}}

*** How do I turn off DEBUG and INFO messages?

{{{ ruby
Ramaze::Log.ignored_tags = [:info, :debug]
}}}

More info on [[http://rubyforge.org/pipermail/ramaze-general/2007-September/000081.html][this mailing list thread]]. Or, to turn off all logging:

{{{ ruby
  Ramaze::Log.loggers = []
}}}


*** How do I save logs to file?

{{{ ruby
# Simple
Ramaze::Log.loggers << Ramaze::Logger::Informer.new( 'ramaze.log' )

# Advanced
  unless Ramaze::Log.loggers.size == 2
    logdir = __DIR__/:logs
    logfile = logdir/"ramaze_#{Time.now.strftime('%Y%m%d%H%M%S')}.log"

    FileUtils.mkdir_p(logdir)
    logger = Informer.new(logfile)
    Ramaze::Log.loggers << Ramaze::Logger::Informer.new(logfile)
  end
}}}


** How do I set Ramaze options?

Via ''Ramaze.start'':

{{{ ruby
Ramaze.start :adapter => adapter
}}}

{{{ruby
Ramaze.start :adapter => :mongrel, :sourcereload => false
}}}
